## taacR 
## Técnicas de Auditoria Assistidas por Computador com R

### Apensar novos registros e campos a uma base de dados

</br>
Algumas vezes surge a necessidade de apensar novos registros a um conjunto de dados.  Esta situação surge, por exemplo, quando temos arquivos mensais contendo dados de faturamento de uma empresa, ou mesmo arquivos contendo as transações realizadas em determinada conta contábil e desejamos juntar estes arquivos para fazer a análise de todo o exercício financeiro. O R dispõe da função ``rbind()`` que nos permite realizar este procedimento.  Vamos ilustrar seu uso com o conjunto de dados ``Invoices.csv``.

Este conjunto de dados possui dados para todo o exercício de 2003.  Para exemplificarmos a utilização da função `rbin()` vamos extrair os registros referentes a janeiro, fevereiro e março e depois vamos juntar os registros destes três meses.

```{r}
# Importação dos dados 
arquivo <- file.path()
faturamento <- read.csv2("Invoices.csv")

# Conversão da coluna Date para o formato de data...
faturamento$Date <- as.Date(faturamento$Date, "%d/%m/%Y")


```




Agora vamos separar os registros do mês de janeiro:

> fatJan <- subset(faturamento, format(Date, "%b") == "jan")
> str(fatJan)
'data.frame':   405 obs. of  8 variables:
 $ Date       :Class 'Date'  num [1:405] 12066 12066 12066 12069 12060 ...
 $ InvoiceNo  : int  20010 20010 20019 20024 20049 20050 20063 20093 20095 ...
 $ CustomerNo : int  10439 10439 10963 10459 10754 10698 10987 10992 10132 ...
 $ SalesPerson: int  19 99 4 24 10 21 2 20 26 20 ...
 $ ProductNo  : int  38 38 16 61 48 47 76 76 56 71 ...
 $ UnitPrice  : num  7.45 7.45 19 31 14 7 9.5 9.5 30 53 ...
 $ Quantity   : int  28 28 19 42 20 38 10 3 5 34 ...
 $ Amount     : num   209  209  361 1302  280 ...

Agora os registros de fevereiro:

> fatFev <- subset(faturamento, format(Date, "%b") == "fev")

E por fim, março:

> fatMar <- subset(faturamento, format(Date, "%b") == "mar")

É razoável admitirmos que os dados em fatJan, fatFev e fatMar, tivessem sido importados dos arquivos fatJan.csv, fatFev.csv e fatMar.csv, contendo, cada um, os registros de faturamento dos meses de janeiro, fevereir e março.

Para combinarmos estes arquivos procedemos da seguinte forma:

> fatTrimestre1 <- rbind(fatJan, fatFev, fatMar)

> head(fatTrimestre1) # Registros Iniciais
         Date InvoiceNo CustomerNo SalesPerson ProductNo UnitPrice Quantity
11 2003-01-14     20010      10439          19        38      7.45       28
12 2003-01-14     20010      10439          99        38      7.45       28
20 2003-01-14     20019      10963           4        16     19.00       19
24 2003-01-17     20024      10459          24        61     31.00       42
49 2003-01-08     20049      10754          10        48     14.00       20
50 2003-01-16     20050      10698          21        47      7.00       38
   Amount
11  208.6
12  208.6
20  361.0
24 1302.0
49  280.0
50  266.0

> tail(fatTrimestre1) #Últimos registros
           Date InvoiceNo CustomerNo SalesPerson ProductNo UnitPrice Quantity
4936 2003-03-02     24936      10538          19        60     263.5       11
4942 2003-03-17     24942      10636          11        55       9.0       45
4952 2003-03-16     24952      10451          24        25      36.0       27
4953 2003-03-29     24953      10621          24        29      43.9       25
4959 2003-03-16     24959      10932          18        53       6.0       25
4999 2003-03-25     24999      10581          25        40      32.8       33
     Amount
4936 2898.5
4942  405.0
4952  972.0
4953 1097.5
4959  150.0
4999 1082.4

É claro que para usarmos a função rbind() os registros a serem apensados devem possuir as mesmas colunas que os registros nos quais serão apensados. 

Apensar Novos Campos

Para realizar esta tarefa o R dispõe da função cbind(), sendo também possível utilizar as funções merge() e data.frame() com esta finalidade. Aqui, iremos ilustrar apenas o uso da função cbind().  O uso da função merge() pode ser visto na página "Combinando Arquivos".

Para ilustrar este procedimento vamos criar os dados a serem utiliados. Serão criados 4 vetores que serão então combinados para formar um conjunto de dados único:

> Coluna1 <- rep(c("Marcos", "Maria", "Carla"), 6) # 18 elementos
> Coluna2 <- rnorm(18) # 18 números aleatórios provenientes de uma normal padrão
> Coluna3 <- sample(c("Jan", "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"), 18, replace=TRUE)

> Novo <- cbind(Coluna1, Coluna2, Coluna3)
> Novo
      Coluna1  Coluna2              Coluna3
 [1,] "Marcos" "0.745116083939915"  "Mar"  
 [2,] "Maria"  "0.85247784205442"   "Fev"  
 [3,] "Carla"  "0.296616605684788"  "Jan"  
 [4,] "Marcos" "0.34177743838317"   "Abr"  
 [5,] "Maria"  "-1.21361886471837"  "Jun"  
 [6,] "Carla"  "-0.09816107520065"  "Jan"  
 [7,] "Marcos" "-0.127215908564143" "Set"  
 [8,] "Maria"  "-0.762337648923552" "Ago"  
 [9,] "Carla"  "1.63335449300431"   "Set"  
[10,] "Marcos" "-0.248601308030468" "Ago"  
[11,] "Maria"  "-1.04018828801494"  "Jul"  
[12,] "Carla"  "-0.99857300205525"  "Abr"  
[13,] "Marcos" "0.16504655561532"   "Set"  
[14,] "Maria"  "0.078794985458832"  "Jul"  
[15,] "Carla"  "0.821395524202317"  "Dez"  
[16,] "Marcos" "-0.38341590731562"  "Dez"  
[17,] "Maria"  "0.0920758433351633" "Nov"  
[18,] "Carla"  "0.505381198136261"  "Dez" 

A função cbind() retorna uma matriz, e no caso presente retornou uma matriz 18 x 3.

Como pode ser visto, todas as colunas estão no formato de caractere, embora a Coluna2 seja numérica.  Esta é uma característica das matrizes; todas as colunas devem ser do mesmo tipo.

Uma outra forma de juntar as colunas é usando a função data.frame().

> Novo2 <- data.frame(Coluna1, Coluna2, Coluna3)
> Novo2
   Coluna1     Coluna2 Coluna3
1   Marcos  0.74511608     Mar
2    Maria  0.85247784     Fev
3    Carla  0.29661661     Jan
4   Marcos  0.34177744     Abr
5    Maria -1.21361886     Jun
6    Carla -0.09816108     Jan
7   Marcos -0.12721591     Set
8    Maria -0.76233765     Ago
9    Carla  1.63335449     Set
10  Marcos -0.24860131     Ago
11   Maria -1.04018829     Jul
12   Carla -0.99857300     Abr
13  Marcos  0.16504656     Set
14   Maria  0.07879499     Jul
15   Carla  0.82139552     Dez
16  Marcos -0.38341591     Dez
17   Maria  0.09207584     Nov
18   Carla  0.50538120     Dez

Para utilizarmos a função cbind() é necessário que a quantidade de registros seja a mesma nos arquivos a serem combinados.

 
