A ordenação de um conjunto de dados com base nos valores de um determinado campo é uma tarefa comum quando se faz análise de dados.  Normalmente o auditor busca, com este procedimento, identificar os maiores valores lançados, as maiores despesas, etc.

Para a execução desta técnica o R dispõe da função order(), cuja utilização será melhor apreendida com um exemplo. Utilizaremos o conjunto de dados "Invoices.csv" para exemplificar sua utilização na ordenação do conjunto de dados com base nos valores das faturas emitidas, o que permitirá identificar as de maior valor.

Os comandos a seguir ilustram o procedimento:

# Importação da base de dados
> faturamento <- read.csv2("Invoices.csv")

# Ordenação da base de dados - ordem crescente (default)
> faturamento.ord1 <- faturamento[order(faturamento$Amount),]

# Ordenação da base de dados em ordem decrescente
> faturamento.ord2 <- faturamento[order(faturamento$Amount, decreasing=TRUE),]

# Apresentação dos 10 menores e os 10 maiores valores faturados
> head(faturamento.ord1, 10)
           Date InvoiceNo CustomerNo SalesPerson ProductNo UnitPrice Quantity
478  21/06/2003     20478      10597          16        34       2.5        2
2566 08/01/2003     22566      10344           6        34       2.5        2
2693 25/03/2003     22693      10666          17        34       2.5        2
3026 14/03/2003     23026      10487          12        34       2.5        2
629  06/01/2003     20629      10304          25        53       6.0        1
494  27/12/2003     20494      10354          17        47       7.0        1
3721 13/10/2003     23721      10325          15        42       7.0        1
2372 22/08/2003     22372      10617          22        34       2.5        3
4362 01/06/2003     24362      10987          12        34       2.5        3
3743 03/09/2003     23743      10338          18        55       9.0        1
     Amount
478     5.0
2566    5.0
2693    5.0
3026    5.0
629     6.0
494     7.0
3721    7.0
2372    7.5
4362    7.5
3743    9.0

> tail(faturamento.ord1, 10)
           Date InvoiceNo CustomerNo SalesPerson ProductNo UnitPrice Quantity
2484 05/11/2003     22484      10360           7        14     263.5       46
3141 29/05/2003     23141      10885           6        14     263.5       46
3211 06/05/2003     23211      10365          25        14     263.5       46
159  30/07/2003     20159      10894           2        60     263.5       47
4284 05/05/2003     24284      10655          23        60     263.5       47
272  06/07/2003     20272      10934          15        60     263.5       48
252  11/07/2003     20252      10636           9        60     263.5       49
1549 12/06/2003     21549      10181          12        14     263.5       49
3184 24/04/2003     23184      10913           9        14     263.5       51
4047 28/02/2003     24047      10073          22        60     263.5       51
      Amount
2484 12121.0
3141 12121.0
3211 12121.0
159  12384.5
4284 12384.5
272  12648.0
252  12911.5
1549 12911.5
3184 13438.5
4047 13438.5

Como pode ser visto acima, a função order() foi utilizada para reordenar as linhas da base de dados e, desta forma, ordená-lo por inteiro (todas as colunas) com base na coluna escolhida. A função order() foi aplicada à coluna "Amount" (que contém o valor das faturas) do conjunto de dados.

Esta função retorna um vetor contendo os índices dos valores em ordem crescente ou decrescente (dependendo do valor atribuído ao argumento decreasing= cujo valor default é "FALSE").   

Caso haja interesse no ordenamento de apenas um vetor, o auditor poderá utilizar a função sort(). O exemplo a seguir ilustra a utilização desta função:

> vetor <- c(13, 7, 2, 9, 4, 20, 46, 78)
> sort(vetor)
[1]  2  4  7  9 13 20 46 78

> sort(vetor, decreasing=TRUE)
[1] 78 46 20 13  9  7  4  2
